# Generated by Django 2.2.4 on 2022-01-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('adminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('userType', models.BooleanField(null=True)),
                ('registerDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('telegramId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=100)),
                ('receiverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverId', to='thanks.User')),
                ('senderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderId', to='thanks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorId', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('menteeId', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('mentorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.Mentor')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docId', models.BigAutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('docType', models.PositiveSmallIntegerField()),
                ('fileUrl', models.ImageField(null=True, upload_to='%Y-%m')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.User')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contentId', models.AutoField(primary_key=True, serialize=False)),
                ('registerDate', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('fileUrl', models.ImageField(null=True, upload_to='contest/')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.User')),
            ],
        ),
    ]
