# Generated by Django 2.2.4 on 2022-01-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
