# Generated by Django 2.2.4 on 2022-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docType',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
