# Generated by Django 2.2.4 on 2022-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
