# Generated by Django 2.2.4 on 2022-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_auto_20220113_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
