# Generated by Django 2.2.4 on 2022-01-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_auto_20220111_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
