# Generated by Django 2.2.4 on 2022-01-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_document_doctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='day',
        ),
        migrations.RemoveField(
            model_name='document',
            name='month',
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
    ]
