# Generated by Django 2.2.4 on 2022-01-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_term_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='activated',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
