# Generated by Django 2.2.4 on 2022-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_auto_20220302_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('registerDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
