# Generated by Django 2.2.4 on 2022-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0004_auto_20220111_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='이제일', max_length=5),
            preserve_default=False,
        ),
    ]
