# Generated by Django 2.2.4 on 2022-03-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0004_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pw',
        ),
    ]
