# Generated by Django 2.2.4 on 2022-01-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0005_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='isMatched',
            field=models.BooleanField(default=False),
        ),
    ]
