# Generated by Django 2.2.4 on 2022-03-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0005_remove_user_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram',
            name='telegramId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
