# Generated by Django 2.2.4 on 2022-01-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0006_mentor_ismatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='mentorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thanks.Mentor'),
        ),
    ]
