# Generated by Django 2.2.4 on 2022-01-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0007_auto_20220111_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('userId', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='semester',
        ),
    ]
