# Generated by Django 2.2.4 on 2022-04-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0007_auto_20220404_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recvChat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recvDaily',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recvNotice',
        ),
    ]
