# Generated by Django 2.2.4 on 2022-05-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0008_auto_20220427_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CSRF',
            field=models.CharField(default='', max_length=64),
        ),
    ]
