# Generated by Django 2.2.4 on 2022-01-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0008_auto_20220111_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='isMatched',
        ),
    ]
