# Generated by Django 2.2.4 on 2022-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0009_remove_mentor_ismatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='userType',
            field=models.BooleanField(null=True),
        ),
    ]
