# Generated by Django 2.2.4 on 2022-01-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0012_mentee_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='isMatched',
        ),
        migrations.AddField(
            model_name='mentor',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='matchedNum',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
